from typing import Any, Dict
from src.domain.models import EvidencePackage

def map_to_razorpay(package: EvidencePackage) -> Dict[str, Any]:
    """
    Map the evidence package to Razorpay's contest API schema.
    Always sets action to 'draft' (NEVER auto-submit).
    """
    return {
        "action": "draft",
        "summary": "Evidence package generated by DisputeShield.",
        "billing_proof": [],
        "proof_of_service": [],
        "access_activity_log": [],
        "customer_communication": [],
        "term_and_conditions": [],
        "explanation_letter": [],
    }
