from enum import Enum

class CardNetwork(str, Enum):
    VISA = "VISA"
    MASTERCARD = "MASTERCARD"

class DisputeCategory(str, Enum):
    FRAUD_UNAUTHORIZED = "FRAUD_UNAUTHORIZED"

class DisputePhase(str, Enum):
    FRAUD = "FRAUD"
    RETRIEVAL = "RETRIEVAL"
    CHARGEBACK = "CHARGEBACK"
    PRE_ARBITRATION = "PRE_ARBITRATION"
    ARBITRATION = "ARBITRATION"

class CaseStatus(str, Enum):
    OPEN = "OPEN"
    INGESTING = "INGESTING"
    ANALYZING = "ANALYZING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    PACKAGE_READY = "PACKAGE_READY"
    SUBMITTED = "SUBMITTED"
    WON = "WON"
    LOST = "LOST"
    CLOSED = "CLOSED"

class EvidenceSourceType(str, Enum):
    ACCESS_LOG = "ACCESS_LOG"
    SERVER_LOG = "SERVER_LOG"
    EMAIL = "EMAIL"
    INVOICE = "INVOICE"
    SCREENSHOT = "SCREENSHOT"
    CSV_LOG = "CSV_LOG"
    JSON_LOG = "JSON_LOG"
    PDF_DOCUMENT = "PDF_DOCUMENT"
    SUPPORT_CHAT = "SUPPORT_CHAT"
    PAYMENT_RECORD = "PAYMENT_RECORD"
    TERMS_OF_SERVICE = "TERMS_OF_SERVICE"
    AUTHENTICATION_LOG = "AUTHENTICATION_LOG"
    DEVICE_LOG = "DEVICE_LOG"
    DOWNLOAD_LOG = "DOWNLOAD_LOG"
    HISTORICAL_TRANSACTION = "HISTORICAL_TRANSACTION"
    OTHER = "OTHER"

class EvidenceType(str, Enum):
    PAYMENT_PROOF = "PAYMENT_PROOF"
    IDENTITY_PROOF = "IDENTITY_PROOF"
    ACCESS_PROOF = "ACCESS_PROOF"
    DELIVERY_PROOF = "DELIVERY_PROOF"
    AUTHENTICATION_PROOF = "AUTHENTICATION_PROOF"
    COMMUNICATION = "COMMUNICATION"
    POLICY_DOCUMENT = "POLICY_DOCUMENT"
    USAGE_METRICS = "USAGE_METRICS"
    HISTORICAL_MATCH = "HISTORICAL_MATCH"

class FactType(str, Enum):
    IP_ADDRESS = "IP_ADDRESS"
    DEVICE_ID = "DEVICE_ID"
    DEVICE_FINGERPRINT = "DEVICE_FINGERPRINT"
    EMAIL_ADDRESS = "EMAIL_ADDRESS"
    TIMESTAMP = "TIMESTAMP"
    CUSTOMER_NAME = "CUSTOMER_NAME"
    ACCOUNT_ID = "ACCOUNT_ID"
    PAYMENT_ID = "PAYMENT_ID"
    ORDER_ID = "ORDER_ID"
    AMOUNT = "AMOUNT"
    CURRENCY = "CURRENCY"
    USER_AGENT = "USER_AGENT"
    GEO_LOCATION = "GEO_LOCATION"
    SESSION_ID = "SESSION_ID"
    DOWNLOAD_HASH = "DOWNLOAD_HASH"
    LICENSE_KEY = "LICENSE_KEY"
    ECI_VALUE = "ECI_VALUE"
    CAVV = "CAVV"
    DS_TRANS_ID = "DS_TRANS_ID"
    AVS_RESULT = "AVS_RESULT"
    CVV_RESULT = "CVV_RESULT"
    ACTION_DESCRIPTION = "ACTION_DESCRIPTION"
    PRODUCT_NAME = "PRODUCT_NAME"
    REFUND_AMOUNT = "REFUND_AMOUNT"
    OTHER = "OTHER"

class RequirementStatus(str, Enum):
    SATISFIED = "SATISFIED"
    PARTIALLY_SATISFIED = "PARTIALLY_SATISFIED"
    MISSING = "MISSING"
    CONTRADICTED = "CONTRADICTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"

class ClaimStatus(str, Enum):
    VERIFIED = "VERIFIED"
    BLOCKED = "BLOCKED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    DRAFT = "DRAFT"

class Recommendation(str, Enum):
    CONTEST = "CONTEST"
    REVIEW = "REVIEW"
    INSUFFICIENT = "INSUFFICIENT"
    ABSTAIN = "ABSTAIN"

class TimelineAnomalyType(str, Enum):
    IMPOSSIBLE_ORDER = "IMPOSSIBLE_ORDER"
    SUSPICIOUS_GAP = "SUSPICIOUS_GAP"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    FUTURE_TIMESTAMP = "FUTURE_TIMESTAMP"
    MISSING_EXPECTED_EVENT = "MISSING_EXPECTED_EVENT"

class ExtractionMethod(str, Enum):
    DETERMINISTIC = "DETERMINISTIC"
    REGEX = "REGEX"
    LLM = "LLM"
    OCR = "OCR"

class ScoringFactorType(str, Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    MISSING = "MISSING"

class ContradictionType(str, Enum):
    """Categories of contradictions the deterministic detector can surface."""
    IP_MISMATCH = "IP_MISMATCH"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    TIMELINE_ORDER = "TIMELINE_ORDER"
    USAGE_BEFORE_PURCHASE = "USAGE_BEFORE_PURCHASE"
    CUSTOMER_STATEMENT_CONFLICT = "CUSTOMER_STATEMENT_CONFLICT"
    FUTURE_TIMESTAMP = "FUTURE_TIMESTAMP"
